apiVersion: v1
kind: ConfigMap
metadata:
  name: basketapi-configmap
data:
  basket.api_url: http://basketapi-service:8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi-deployment
  labels:
    app: basket.api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket.api
  template:
    metadata:
      labels:
        app: basket.api
    spec:
      containers:
        - name: basket-api
          image: basket.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__BasketDB
              valueFrom:
                configMapKeyRef:
                  name: basketdb-configmap
                  key: connection_string
            - name: ConnectionStrings__IdentityAuthority
              valueFrom:
                configMapKeyRef:
                  name: identityserver-configmap
                  key: identityserver_url
            - name: ConnectionStrings__GrpcDiscountUrl
              valueFrom:
                configMapKeyRef:
                  name: discountgrpc-configmap
                  key: discount.grpc_url
            - name: ConnectionStrings__EventBusAddress
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: basketapi-service
spec:
  type: NodePort
  selector:
    app: basket.api
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 80
      nodePort: 30002