apiVersion: v1
kind: Secret
metadata:
  name: catalogdb-secret
type: Opaque
data:
  mongo-root-username: Y2F0YWxvZy5kYi51c2Vy
  mongo-root-password: Y2F0YWxvZy5kYi5wYXNzd29yZA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogdb-configmap
data:
  connection_string: mongodb://catalog.db.user:catalog.db.password@catalogdb-service:27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb-deployment
  labels:
    app: catalog.db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog.db
  template:
    metadata:
      labels:
        app: catalog.db
    spec:
      containers:
        - name: catalog-db
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: catalogdb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalogdb-secret
                  key: mongo-root-password
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogdb-service
spec:
  selector:
    app: catalog.db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017