apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogapi-configmap
data:
  catalog.api_url: http://catalogapi-service:8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi-deployment
  labels:
    app: catalog.api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog.api
  template:
    metadata:
      labels:
        app: catalog.api
    spec:
      containers:
        - name: catalog-api
          image: catalog.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__CatalogDB
              valueFrom:
                configMapKeyRef:
                  name: catalogdb-configmap
                  key: connection_string
            - name: ConnectionStrings__IdentityAuthority
              valueFrom:
                configMapKeyRef:
                  name: identityserver-configmap
                  key: identityserver_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  type: NodePort
  selector:
    app: catalog.api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 30001