apiVersion: v1
kind: ConfigMap
metadata:
  name: discountgrpc-configmap
data:
  discount.grpc_url: http://discountgrpc-service:8004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountgrpc-deployment
  labels:
    app: discount.grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount.grpc
  template:
    metadata:
      labels:
        app: discount.grpc
    spec:
      containers:
        - name: discount-grpc
          image: discount.grpc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DiscountDB
              valueFrom:
                configMapKeyRef:
                  name: discountdb-configmap
                  key: connection_string
            - name: ConnectionStrings__IdentityAuthority
              valueFrom:
                configMapKeyRef:
                  name: identityserver-configmap
                  key: identityserver_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: discountgrpc-service
spec:
  type: NodePort
  selector:
    app: discount.grpc
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 80
      nodePort: 30004