apiVersion: v1
kind: Secret
metadata:
  name: discountdb-secret
type: Opaque
data:
  postgres-root-username: ZGlzY291bnQuZGIudXNlcg==
  postgres-root-password: ZGlzY291bnQuZGIucGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: discountdb-configmap
data:
  connection_string: Server=discountdb-service;Port=5432;Database=DiscountDb;User Id=discount.db.user;Password=discount.db.password;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountdb-deployment
  labels:
    app: discount.db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount.db
  template:
    metadata:
      labels:
        app: discount.db
    spec:
      containers:
        - name: discount-db
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: discountdb-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discountdb-secret
                  key: postgres-root-password
            - name: POSTGRES_DB
              value: DiscountDb
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: discountdb-service
spec:
  selector:
    app: discount.db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432