apiVersion: v1
kind: ConfigMap
metadata:
  name: discountapi-configmap
data:
  discount.api_url: http://discountapi-service:8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountapi-deployment
  labels:
    app: discount.api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount.api
  template:
    metadata:
      labels:
        app: discount.api
    spec:
      containers:
        - name: discount-api
          image: discount.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DiscountDB
              valueFrom:
                configMapKeyRef:
                  name: discountdb-configmap
                  key: connection_string
            - name: ConnectionStrings__IdentityAuthority
              valueFrom:
                configMapKeyRef:
                  name: identityserver-configmap
                  key: identityserver_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: discountapi-service
spec:
  type: NodePort
  selector:
    app: discount.api
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 80
      nodePort: 30003