apiVersion: v1
kind: ConfigMap
metadata:
  name: identityserver-configmap
data:
  identityserver_url: http://identityserver-service:1080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityserver-deployment
  labels:
    app: identityserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityserver
  template:
    metadata:
      labels:
        app: identityserver
    spec:
      containers:
        - name: identityserver
          image: identityserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__WebAppClient
              valueFrom:
                  configMapKeyRef:
                    name: shoppingwebapp-configmap
                    key: shoppingwebapp_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: identityserver-service
spec:
  type: NodePort
  selector:
    app: identityserver
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 80
      nodePort: 31080