apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelotapigw-configmap
data:
  ocelot.apigw_url: http://ocelotapigw-service:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapigw-deployment
  labels:
    app: ocelot.apigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelot.apigw
  template:
    metadata:
      labels:
        app: ocelot.apigw
    spec:
      containers:
        - name: ocelotapigw
          image: ocelot.apigw:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
            - name: ConnectionStrings__IdentityAuthority
              valueFrom:
                configMapKeyRef:
                  name: identityserver-configmap
                  key: identityserver_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: ocelotapigw-service
spec:
  type: NodePort
  selector:
    app: ocelot.apigw
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080