apiVersion: v1
kind: ConfigMap
metadata:
  name: orderingapi-configmap
data:
  ordering.api_url: http://orderingapi-service:8005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderingapi-deployment
  labels:
    app: ordering.api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering.api
  template:
    metadata:
      labels:
        app: ordering.api
    spec:
      containers:
        - name: ordering-api
          image: ordering.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__OrderingDB
              valueFrom:
                configMapKeyRef:
                  name: orderingdb-configmap
                  key: connection_string
            - name: ConnectionStrings__IdentityAuthority
              valueFrom:
                configMapKeyRef:
                  name: identityserver-configmap
                  key: identityserver_url
            - name: ConnectionStrings__EventBusAddress
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-configmap
                  key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: orderingapi-service
spec:
  type: NodePort
  selector:
    app: ordering.api
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 80
      nodePort: 30005