apiVersion: v1
kind: ConfigMap
metadata:
  name: shoppingwebapp-configmap
data:
  shoppingwebapp_url: http://shoppingwebapp-service:8181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingwebapp-deployment
  labels:
    app: shopping.webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping.webapp
  template:
    metadata:
      labels:
        app: shopping.webapp
    spec:
      containers:
        - name: shoppingwebapp
          image: shopping.webapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__IdentityAuthority
              valueFrom:
                configMapKeyRef:
                  name: identityserver-configmap
                  key: identityserver_url
            - name: ConnectionStrings__GatewayAddress
              valueFrom:
                configMapKeyRef:
                  name: ocelotapigw-configmap
                  key: ocelot.apigw_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingwebapp-service
spec:
  type: NodePort
  selector:
    app: shopping.webapp
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 80
      nodePort: 30181