version: '3.4'

services:
  # Portainer
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  # Message broker
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Catalog.API Services
  catalog.db:
    container_name: catalog.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_data:/data/configdb

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:CatalogDB=mongodb://catalog.db:27017
      - ConnectionStrings:IdentityAuthority=http://identityserver
      - ConnectionStrings:ElasticSearchUri=http://elasticsearch:9200
      - ConnectionStrings:ZipkinUri=http://zipkinserver:9411
    depends_on:
      - catalog.db
    ports:
      - "8001:80"

  # Basket.API Services
  basket.db:
    container_name: basket.db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:BasketDB=basket.db:6379
      - ConnectionStrings:IdentityAuthority=http://identityserver
      - ConnectionStrings:GrpcDiscountUrl=http://discount.grpc
      - ConnectionStrings:EventBusAddress=amqp://guest:guest@rabbitmq:5672
      - ConnectionStrings:ElasticSearchUri=http://elasticsearch:9200
      - ConnectionStrings:ZipkinUri=http://zipkinserver:9411
    depends_on:
      - basket.db
      - discount.grpc
      - rabbitmq
    ports:
      - "8002:80"

  # Discount.API Services
  discount.db:
    container_name: discount.db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DiscountDB=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;
      - ConnectionStrings:IdentityAuthority=http://identityserver
      - ConnectionStrings:ElasticSearchUri=http://elasticsearch:9200
      - ConnectionStrings:ZipkinUri=http://zipkinserver:9411
    depends_on:
      - discount.db
    ports:
      - "8003:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DiscountDB=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;
      - ConnectionStrings:ElasticSearchUri=http://elasticsearch:9200
    depends_on:
      - discount.db
    ports:
      - "8004:80"

  # Ordering.API Services
  ordering.db:
    container_name: ordering.db
    environment:
      - SA_PASSWORD=JaaP12345678
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:IdentityAuthority=http://identityserver
      - ConnectionStrings:OrderingDB=Server=ordering.db;Database=OrderDb;User Id=sa;Password=JaaP12345678;
      - ConnectionStrings:EventBusAddress=amqp://guest:guest@rabbitmq:5672
      - ConnectionStrings:ElasticSearchUri=http://elasticsearch:9200
      - ConnectionStrings:ZipkinUri=http://zipkinserver:9411
    depends_on:
      - ordering.db
      - rabbitmq
    ports:
      - "8005:80"

  # Ocelot.ApiGw
  ocelot.apigw:
    container_name: ocelot.apigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:IdentityAuthority=http://identityserver
      - ConnectionStrings:ElasticSearchUri=http://elasticsearch:9200
      - ConnectionStrings:ZipkinUri=http://zipkinserver:9411
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "80:80"

  # Shoppin.Aggregator
  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings:CatalogUrl=http://catalog.api
      - ApiSettings:BasketUrl=http://basket.api
      - ApiSettings:OrderingUrl=http://ordering.api
      - ConnectionStrings:ElasticSearchUri=http://elasticsearch:9200
      - ConnectionStrings:ZipkinUri=http://zipkinserver:9411
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "8006:80"

  # Shopping.WebApp
  shopping.webapp:
    container_name: shopping.webapp
    depends_on:
      - ocelot.apigw
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:IdentityAuthority=http://identityserver
      - ConnectionStrings:GatewayAddress=http://ocelot.apigw
      - ConnectionStrings:ElasticSearchUri=http://elasticsearch:9200
      - Serilog__MinimumLevel__Override__Shopping.WebApp.Services=Information
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=joadarpe
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/shopping.webapp.pfx
      - WaitAndRetry__RetryCount=3
      - WaitAndRetry__ExponentialBackoffMultiplier=1
      - CircuitBreaker__EventsBeforeBreaking=6
      - CircuitBreaker__DurationOfBreak=30
    ports:
      - "8181:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  # IdentityServer
  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:WebAppClient=https://shopping.webapp
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=joadarpe
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/identityserver.pfx
    ports:
      - "1080:80"
      - "1443:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  # Observability services
  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch_data:/usr/share/elasticsearch/data   

  kibana:
    container_name: kibana
    environment:        
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601"

  # Status.WebApp
  status.webapp:
    container_name: status.webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://catalog.api/health
      - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://basket.api/health
      - HealthChecksUI__HealthChecks__2__Name=Discount Health Check
      - HealthChecksUI__HealthChecks__2__Uri=http://discount.api/health
      - HealthChecksUI__HealthChecks__3__Name=Ordering Health Check
      - HealthChecksUI__HealthChecks__3__Uri=http://ordering.api/health
      - HealthChecksUI__HealthChecks__4__Name=Shopping Aggregator Health Check
      - HealthChecksUI__HealthChecks__4__Uri=http://shopping.aggregator/health
      - HealthChecksUI__HealthChecks__5__Name=Shopping WebApp Health Check
      - HealthChecksUI__HealthChecks__5__Uri=https://shopping.webapp:8181/health
    ports:
      - "8282:80"

  # ZipkinServer 
  zipkinserver:
    container_name: zipkinserver
    mem_reservation: 300m
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "9411:9411"