version: '3.4'

services:
# Portainer
  portainer:
    image: portainer/portainer-ce

# Catalog.API Services
  catalog.db:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: services/catalog/Catalog.API/Dockerfile

# Basket.API Services
  basket.db:
    image: redis:alpine

  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: services/basket/Basket.API/Dockerfile

volumes:
  portainer_data:
  mongo_data:
  redis_data:
