version: '3.4'

services:
  # Portainer
  portainer:
    image: portainer/portainer-ce

  # Message broker
  rabbitmq:
    image: rabbitmq:3-management-alpine

  # Catalog.API Services
  catalog.db:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: services/catalog/Catalog.API/Dockerfile

  # Basket.API Services
  basket.db:
    image: redis:alpine

  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: services/basket/Basket.API/Dockerfile

  # Discount.API Services
  discount.db:
    image: postgres

  discount.api:
    image: ${DOCKER_REGISTRY-}discount.api
    build:
      context: .
      dockerfile: services/discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discount.grpc
    build:
      context: .
      dockerfile: services/discount/Discount.gRPC/Dockerfile

  # Ordering.API Services
  ordering.db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  ordering.api:
    image: ${DOCKER_REGISTRY-}ordering.api
    build:
      context: .
      dockerfile: services/ordering/Ordering.API/Dockerfile

volumes:
  portainer_data:
  mongo_data:
  redis_data:
  postgres_data:
  rabbitmq_data:
